<?php
@include("../../inc/header.php");

/*
		SoftName : EmpireBak
		Author   : wm_chief
		Copyright: Powered by www.phome.net
*/

E_D("DROP TABLE IF EXISTS `www_96kaifa_com_ecms_danji_data_1`;");
E_C("CREATE TABLE `www_96kaifa_com_ecms_danji_data_1` (
  `id` int(10) unsigned NOT NULL DEFAULT '0',
  `classid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `keyid` varchar(255) NOT NULL DEFAULT '',
  `dokey` tinyint(1) NOT NULL DEFAULT '0',
  `newstempid` smallint(5) unsigned NOT NULL DEFAULT '0',
  `closepl` tinyint(1) NOT NULL DEFAULT '0',
  `haveaddfen` tinyint(1) NOT NULL DEFAULT '0',
  `infotags` varchar(80) NOT NULL DEFAULT '',
  `writer` varchar(30) NOT NULL DEFAULT '',
  `befrom` varchar(60) NOT NULL DEFAULT '',
  `newstext` mediumtext NOT NULL,
  PRIMARY KEY (`id`),
  KEY `classid` (`classid`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('1','7','','0','0','0','0','','','','<p>这游戏一般人可玩不了。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>利用加减法，计算图形即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('2','7','','0','0','0','0','','','','<p>小心你头上的巫婆。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃得分，记得躲避障碍物哦。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('3','7','','0','0','0','0','','','','<p>我达到了2级，圣诞节给剁手党的一次狂欢。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>经营商场，完成店铺布置完成任务即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('4','7','','0','0','0','0','','','','<p>万圣节到了，给自己做个专属蛋糕吧!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“play”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>按照自己的喜好搭配，制作万圣节蛋糕。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('5','7','','0','0','0','0','','','','<p>传说这是一个大神都“跪舔”的游戏。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“play”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>躲避障碍物，吃掉金币即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('6','7','','0','0','0','0','','','','<p>你能做到一点过关吗?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>点击小水滴，小水滴自行分裂引爆其他水滴，达到数量要求即可过关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('7','7','','0','0','0','0','','','','<p>少年，不要怂，赶紧跑!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，选择关卡即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃，吃掉金币即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('8','7','','0','0','0','0','','','','<p>要记得射准一点哦。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可。</p><p><strong>游戏玩法：</strong></p><p>在规定时间内，传球到球门前射门，射进即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('9','7','','0','0','0','0','','','','<p><strong>如何开始：</strong></p><p>游戏加载完毕，点击开始即可。</p><p><strong>游戏玩法：</strong></p><p>在规定时间看圣诞树得分，记得躲避障碍物哦。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('10','7','','0','0','0','0','','','','<p>需要一点点运气和智慧。</p><p><strong>如何开始：</strong></p><p>点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>优先将棋子全部抵达终点，即可获胜。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('11','7','','0','0','0','0','','','','<p>小狗可以潜水的你见过吗?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>躲避障碍物，收集金币和空气即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('12','7','','0','0','0','0','','','','<p>在遥远的地方，有地狱的边境。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可。</p><p><strong>游戏玩法：</strong></p><p>躲避怪物，收集阳光即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('13','7','','0','0','0','0','','','','<p>你的猫可以活多久?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制猫咪跳跃，跳到下一个灯上即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('14','7','','0','0','0','0','','','','<p>我玩到了第十关，你的智商有多高呢?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>在规定时间内，完成目标，即可过关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('15','7','','0','0','0','0','','','','<p>我的代号是“子弹”，你的代号是什么?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制子弹飞行速度，躲避障碍物即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('16','7','','0','0','0','0','','','','<p>寿司随意吃，看你能串多少!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“play”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>抓住时机串寿司，串到越多得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('17','7','','0','0','0','0','','','','<p>宫逗中，你能跑多远呢?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>连续点击屏幕前进，松开后退，记得躲避障碍物。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('18','7','','0','0','0','0','','','','<p>我被封为丫鬟，我不说话，说话会惹祸。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始。</p><p><strong>游戏玩法：</strong></p><p>屏幕向右滑动，躲避障碍物。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('19','7','','0','0','0','0','','','','<p>兄弟快点跑。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制人物移动，躲避障碍物，跑的越远得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('20','7','','0','0','0','0','','','','<p>在皇宫中你能飞多久?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制人物向上或向下，躲避障碍物。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('21','7','','0','0','0','0','','','','<p>我有一个梦想，就是开个烧烤店。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>移动标有数字的烧烤进行合适的叠放。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('22','7','','0','0','0','0','','','','<p>根本停不下来的感觉。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕使砖块停止，在有限的空间里走过越长的路，得分也就越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('23','7','','0','0','0','0','','','','<p>划船不用桨，全靠浪!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制左右方向，躲避障碍物。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('24','7','','0','0','0','0','','','','<p>消灭丧尸，瞄准，点击，打爆他们的头。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕进行射击，消灭丧尸即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('25','7','','0','0','0','0','','','','<p>带你走进可乐工厂的秘密。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“PLAY”，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>将可乐装入瓶中，与绿色线重合即可赚钱得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('26','7','','0','0','0','0','','','','<p>三眼归来，帮忙找到所有的能量球!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>在房间内找到25个能量球，即可通关得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('27','7','','0','0','0','0','','','','<p>经典跑酷类游戏，全新玩法演绎。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击屏幕-播放键，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>方向键控制人物移动，躲避障碍物，吃金币得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('28','7','','0','0','0','0','','','','<p>据说能坚持到100分的都是神。</p><p><strong>游戏玩法：</strong></p><p>躲避障碍物，即可得分。</p><p><strong>游戏目标：</strong></p><p>躲避障碍物越多，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('29','7','','0','0','0','0','','','','<p>不要太崇拜我，我会不好意思的。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>躲避行星，保护好种子即可。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('30','7','','0','0','0','0','','','','<p>你看到我的滑板鞋了吗?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃，躲避障碍物，吃金币得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('31','7','','0','0','0','0','','','','<p>你想当村长还是镇长呢?</p><p><strong>游戏玩法</strong>：</p><p>根据相同颜色，消除并升级为一个高级建筑。</p><p><strong>游戏目标</strong>：</p><p>建筑等级越高，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('32','7','','0','0','0','0','','','','<p style=\\\\\"white-space: normal;\\\\\">晒智商的时间到了，你敢来吗?</p><p style=\\\\\"white-space: normal;\\\\\"><strong>如何开始：</strong></p><p style=\\\\\"white-space: normal;\\\\\">游戏加载完毕，点击播放键即可开始游戏。</p><p style=\\\\\"white-space: normal;\\\\\"><strong>游戏玩法：</strong></p><p style=\\\\\"white-space: normal;\\\\\">点击屏幕消除相同部分，规定时间内获得更高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('33','7','','0','0','0','0','','','','<p>看到企鹅不要太激动，支援随时会来到。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>消除颜色相同的方块，让探员顺利上岸。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('34','7','','0','0','0','0','','','','<p>考验你眼力的时候到了。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>控制雪球推倒企鹅，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('35','7','','0','0','0','0','','','','<p>这个圣诞节谁能与我一战!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>将相同图案连接消除，即可得分。在规定时间内消除全部图案，即可通关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('36','7','','0','0','0','0','','','','<p>探险路上困难多，要小心了!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃，控制人物落到下一点，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('37','7','','0','0','0','0','','','','<p>眼疾手快，思维敏捷说的就是我!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，选择国家，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>在规定时间内，将相同的丸子用直线连接起来，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('38','7','','0','0','0','0','','','','<p>热血乒乓，燥起来!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>证接到乒乓球，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('39','7','','0','0','0','0','','','','<p>小猪别怂，小猪快跑!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击动画，开始游戏即可。</p><p><strong>游戏玩法：</strong></p><p>躲避障碍物和杀猪刀追赶，吃金币得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('40','7','','0','0','0','0','','','','<p>据说很少有人能超过200分哦。</p><p><strong>如何开始：<br/></strong>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：<br/></strong>补充缺少的砖块，消除整行砖块即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('41','7','','0','0','0','0','','','','<p>快点逃离这个鬼地方。</p><p><strong>如何开始：<br/></strong>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：<br/></strong>躲避障碍物，吃掉星星即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('42','7','','0','0','0','0','','','','<p>据说能爬到100层的都是疯子。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制人物移动，躲避炸弹向上爬。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('43','7','','0','0','0','0','','','','<p>你能控制几根粉笔呢？<br/><strong>如何开始：</strong><br/>游戏加载完毕，点击播放键即可开始游戏。<br/><strong>游戏玩法：</strong><br/>控制两本粉笔躲避障碍物，画的越长得分越高。<br/></p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('44','7','','0','0','0','0','','','','<p>生存还是死亡，这是个问题。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”-选择关卡，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>方向键控制人物移动，击杀丧尸得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('45','7','','0','0','0','0','','','','<p>李小龙再也不用担心找不到师父了！<br/><strong>如何开始：</strong><br/>游戏加载完毕，点击“开始游戏”即可。<br/><strong>游戏玩法：</strong><br/>点击屏幕左右控制叶问打败对手。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('46','7','','0','0','0','0','','','','<p>据说手残党一辈子也不能通关。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>按照每关指示，点击屏幕操作，通关即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('47','7','','0','0','0','0','','','','<p>这游戏也太好玩了，据说能玩到400分的人还没出现!</p><p><strong>游戏玩法</strong>：</p><p>控制小黑人，准确的落在下一个悬崖边。</p><p><strong>游戏目标：</strong></p><p>路过悬崖越多，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('48','7','','0','0','0','0','','','','<p>最酷炫的玩法，最经典的跑酷游戏!</p><p>游戏玩法：</p><p>躲避障碍物，吃掉道具得分。</p><p>游戏目标：</p><p>吃道具越多，跑的越远，得分也越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('49','7','','0','0','0','0','','','','<p>圣诞节，一个人也可以这样过。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始。</p><p><strong>游戏玩法：</strong></p><p>在规定时间内，消除得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('50','7','','0','0','0','0','','','','<p>熊猫消水果，你有见过吗?</p><p><strong>游戏玩法：</strong></p><p>在规定时间内完成任务，即可通关得分。</p><p><strong>游戏目标：</strong></p><p>尽可能多的增加游戏时间，闯过更多的关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('51','7','','0','0','0','0','','','','<p>大猩猩最喜欢吃的就是香蕉了，如果你没给它吃到香蕉，它可是会发怒的!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”，再点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>必须准确无误的将香蕉投到大猩猩身上。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('52','7','','0','0','0','0','','','','<p>我是丘比特转世，快来挑战我吧!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>力度条控制在红色区域，射中苹果即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('53','7','','0','0','0','0','','','','<p>经典游戏，全新玩法，就是这么任性。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制贪吃蛇移动，吃掉苹果并躲避障碍物。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('54','7','','0','0','0','0','','','','<p>智力大考验，瞬间感觉该补补脑了!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>凑齐一列或一行，即可消除得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('55','7','','0','0','0','0','','','','<p>跳的根本停不下来。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕，控制左右两边怪物跳跃，只有大的可以跳过小的。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('56','7','','0','0','0','0','','','','<p>你的脑子够活跃么，来试试看吧。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制汽车，撞到障碍物或错过星星，就算失败。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('57','7','','0','0','0','0','','','','<p>忍者大逃亡，体验忍者刺激的飞檐走壁。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制忍者左右跳跃，躲避障碍物跳到最高处，得分就越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('58','7','','0','0','0','0','','','','<p>是男人就来接受战火的洗礼吧!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制人物，躲避火箭和炸弹，坚持时间越长得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('59','7','','0','0','0','0','','','','<p>你是神枪手吗?快来试试吧。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>拦截飞来的目标，越靠近中心，打靶环数越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('60','7','','0','0','0','0','','','','<p>天下武功，唯快不破。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>抓住下落的小动物，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('61','7','','0','0','0','0','','','','<p>要快点砍，小心天上的墓碑。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕控制大叔砍树，砍得越多得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('62','7','','0','0','0','0','','','','<p>每天甜蜜多一点，烦恼忧愁就会少一点!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>根据要求完成任务，即可进行下一关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('63','7','','0','0','0','0','','','','<p>一二三四五，景阳冈上打老虎!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击屏幕，选择游戏模式和关卡，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>建造蒸笼烹饪食物，在老虎吃光食物之前，消灭老虎。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('64','7','','0','0','0','0','','','','<p>只有1%的人第一次玩可以挑战成功，你是这1%的人吗?</p><p><strong>游戏玩法：</strong></p><p>在规定时间内，将所有的图案拼好。</p><p><strong>游戏目标：</strong></p><p>用时越少，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('65','7','','0','0','0','0','','','','<p>终极平衡挑战，挑战了不起!</p><p><strong>游戏玩法：</strong></p><p>点击屏幕左右键，控制平衡。</p><p><strong>游戏目标：</strong></p><p>坚持时间越长，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('66','7','64','0','0','0','0','','','','<p>弹射熊猫，好玩而不简单!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，选择关卡即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>左右两侧控制熊猫弹射，吃掉所有水果即可通关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('67','7','','0','0','0','0','','','','<p>我玩了12分，初级诅咒师，刚刚入门还需努力!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“start”即可开始游戏</p><p><strong>游戏玩法：</strong></p><p>在敌人落地之前，根据敌人头上的圈圈，画出相同图案，即可消灭敌人获得金币。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('68','7','','0','0','0','0','','','','<p>我在人从哪里来玩了1268分，终于知道人是怎么来的了!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始”即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>1.低级物种合成高级物种，低级物种消除。</p><p>2.物种合成越高级，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('69','7','','0','0','0','0','','','','<p>我玩到第6关，智商碾压一切，求超越!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，选择关卡即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕方向键控制贪吃鸟移动，吃掉所有食物即可3星通关!</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('70','7','','0','0','0','0','','','','<p>超级劲爆的橄榄球比赛开始了，为了胜利，勇敢冲锋吧!</p><p><strong>游戏玩法：</strong></p><p>撞倒你面前的对手，保护橄榄球。</p><p><strong>游戏目标：</strong></p><p>不要被对手抓到，记得瞄准对面哦。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('71','7','','0','0','0','0','','','','<p>我玩了100分，你又能射中几分呢，少年要来一发么?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，既可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>瞄准射击目标，集中得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('72','7','','0','0','0','0','','','','<p>看你眼力有多精，看你反应有多灵，就看你到底行不行!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>瞄准洞口，把炮炮射进洞得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('73','7','','0','0','0','0','','','','<p>刺激赛艇!带你装逼带你浪!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕点击播放键，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>左右键控制小艇移动，点击越快速度越快。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('74','7','','0','0','0','0','','','','<p>我玩了2300分，以你的智商，能玩多少分呢?</p><p><strong>游戏玩法：</strong></p><p>将管道连接到另一侧，完成管道消除。</p><p><strong>游戏目标：</strong></p><p>在规定时间内，尽可能多的消除管道，获得高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('75','7','','0','0','0','0','','','','<p>该不该摘下重重的壳，寻找到底哪里有蓝天。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃，双击屏幕跳跃一层，层数越高，得分越多。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('76','7','','0','0','0','0','','','','<p>动动你的小鼠标，帮张小盒穿越车海吧</p><p><strong>游戏玩法：</strong></p><p>鼠标按住小盒向下走动，松开小盒停止走动</p><p><strong>游戏目标：</strong></p><p>规定时间内穿越更多马路</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('77','7','','0','0','0','0','','','','<p>只怪自己当初物理没学好，还是怪物理老师死得早?</p><p><strong>游戏玩法：</strong></p><p>左右键控制向左或者向右移动。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('78','7','','0','0','0','0','','','','<p>糖果乐园，糖果消除的又一款爱不释手的游戏。<br/></p><p><strong>操作指南：</strong></p><p>点击相邻的糖果消除它们，一次性消除的糖果越多，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('79','7','','0','0','0','0','','','','<p>你的数学是哪个老师教的?快来证明一下你的实力吧。</p><p><strong>游戏玩法：</strong></p><p>规定时间内按顺序找到下一个数字。</p><p><strong>游戏目标：</strong></p><p>找到更多数字，获得高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('80','7','','0','0','0','0','','','','<p>你能闯到第几关呢?现在就进入游戏中挑战吧!</p><p><strong>游戏玩法：</strong></p><p>游戏中，你得在相应的时间内将游戏中的路径全部都描画出，但是不能重复哦。</p><p><strong>游戏目标：</strong></p><p>快速描画出路径，闯入下一关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('81','7','','0','0','0','0','','','','<p>据说能玩到100分的全是大神!</p><p><strong>游戏玩法：</strong></p><p>改变道路方向，控制收集车收集香蕉即可得分。</p><p><strong>游戏目标：</strong></p><p>收集香蕉越多，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('82','7','','0','0','0','0','','','','<p>最虐心的休闲游戏，你准备好了吗?</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>准备的把苹果接到篮子里，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('83','7','','0','0','0','0','','','','<p>玩的就是心跳，你得个5分我看看?</p><p><strong>游戏玩法</strong>：</p><p>点击屏幕跳跃，双击可连跳。</p><p><strong>游戏目标</strong>：</p><p>跳过障碍物越多，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('84','7','','0','0','0','0','','','','<p>　　上天入地跃龙门的小青蛙也不服输，也要来挑战史上最难游戏小游戏啦!通过第一大要求：安静的环境关键是无人骚扰、眼明手快!快来挑战吧!</p><p>如何开始：</p><p>游戏加载完毕，点击播放键，选择关卡即可开始游戏。</p><p>游戏玩法：</p><p>根据每关要求，在规定时间内完成任务即可通关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('85','7','','0','0','0','0','','','','<p>再也停不下来，谁也别拦我。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃，吃掉寿司即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('86','7','','0','0','0','0','','','','<p>我过了十关，好有趣的拼图游戏</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键即可进入游戏。</p><p><strong>游戏玩法：</strong></p><p>将图案拼接完毕即可过关，拼图可重叠。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('87','7','','0','0','0','0','','','','<p>人生就像茶几，上面放满了杯具。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击“开始游戏”即可。</p><p><strong>游戏玩法：</strong></p><p>左边的杯子滑到右手边时点击屏幕，右边亦然。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('88','7','','0','0','0','0','','','','<p>你有能力在浩瀚无垠的宇宙中遨游吗?</p><p><strong>游戏玩法：</strong></p><p>摆脱星球引力，穿越到下一个星球即可得分。</p><p><strong>游戏目标：</strong></p><p>不断穿越星球，获得更高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('89','7','','0','0','0','0','','','','<p>据说只有3%的人能超过35分。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕跳跃，躲避障碍物。</p><p><strong>游戏目标：</strong></p><p>躲避障碍物越多，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('90','7','','0','0','0','0','','','','<p>这是一个个玄妙的圆圈圈，而你就在上面转转转，然后......</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，选择游戏模式即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>点击屏幕可进出圆圈，也可跳到另一个圈圈，收集所有晶体并到达绿色圆圈即可过关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('91','7','','0','0','0','0','','','','<p>挖掘技术哪家强? 就看你强不强!</p><p><strong>如何开始</strong>：</p><p>游戏加载完毕，点击“挖起来”，点击屏幕即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>规定时间内，疯狂点击屏幕挖掘得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('92','7','','0','0','0','0','','','','<p>密集恐惧症，请谨慎点击此游戏!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，再点击“开始”，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>从1点骰子开始合成消除，合成点数越高，得分越多。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('93','7','','0','0','0','0','','','','<p>如今身在江湖，怎么能让江湖没有你的传说。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击屏幕准备，再点击屏幕开始，即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>你脚下的竹子会下沉，在它下沉之前跳跃空中，击打两侧的飞镖，即可得分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('94','7','','0','0','0','0','','','','<p>独自玩很爽，分享玩更佳!</p><p><strong>游戏玩法：</strong></p><p>将上方出现的数字，落在合适的位置，方块上的数字相加消除。</p><p><strong>游戏目标：</strong></p><p>数字越大，得分越高。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('95','7','','0','0','0','0','','','','<p>难!跟登天一样难!<br/></p><p><strong>游戏玩法：</strong></p><p>躲避怪物，鼠标点击屏幕登高，一路登上去。</p><p><strong>游戏目标：</strong></p><p>登的越高，获得越高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('96','7','','0','0','0','0','','','','<p>执子之手，最后是坟墓吗?努力后就知道了!</p><p><strong>游戏玩法：</strong></p><p>合成方格内随机出现的字，直到消除完毕。</p><p><strong>游戏目标：</strong></p><p>一直合成到最后，看看是什么字?</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('97','7','','0','0','0','0','','','','<p>公主被劫持，身为忍者，责任重大，赶快前去营救吧。</p><p><strong>游戏玩法：</strong></p><p>游戏总共只有两个功能键——向左或者向右。</p><p><strong>游戏目标</strong>：</p><p>躲避障碍物，营救公主。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('98','7','','0','0','0','0','','','','<p><span style=\\\\\"color: rgb(51, 51, 51); font-family: &#39;Microsoft Yahei&#39;, 宋体, &#39;Arial Narrow&#39;; font-size: 12px; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(255, 255, 255);\\\\\"></span>功夫熊猫来啦，快来看熊猫如何成为功夫大师。</p><p><strong>游戏玩法：</strong></p><p>长按屏幕调整熊猫弹簧的强度，跳到石柱上。</p><p><strong>游戏目标：</strong></p><p>跳的更远，获得高分。</p><p><span style=\\\\\"color: rgb(51, 51, 51); font-family: &#39;Microsoft Yahei&#39;, 宋体, &#39;Arial Narrow&#39;; font-size: 12px; font-variant-ligatures: normal; orphans: 2; widows: 2; background-color: rgb(255, 255, 255);\\\\\"></span><br/></p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('99','7','','0','0','0','0','','','','<p>珍爱生命，远离电线。</p><p><strong>游戏玩法：</strong></p><p>鼠标控制小钢圈，远离电线坚持住。</p><p><strong>游戏目标：</strong></p><p>坚持越久，得分越高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('100','7','','0','0','0','0','','','','<p>锻炼你的反应力，快来吃苹果吧!</p><p><strong>游戏玩法：</strong></p><p>点击屏幕上的苹果，一个都不能放过。</p><p><strong>游戏目标：</strong></p><p>在规定时间内吃掉更多苹果。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('101','7','','0','0','0','0','','','','<p>自从得了神经病,整个人都精神了</p><p><strong>游戏玩法：</strong></p><p>鼠标点击圆圈，点击过的圆圈变为橙色，利用橙色圆圈围住神经猫</p><p><strong>游戏目标：</strong></p><p>用最少的步数去围住神经猫</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('102','7','','0','0','0','0','','','','<p>你有没有在放学后和朋友一起在黑板上玩游戏？就是这样!<br/><strong>如何开始</strong>：<br/>游戏加载完毕，点击播放键即可开始游戏。<br/><strong>游戏目标：</strong><br/>挑战更多关卡，成为涂鸦高手<br/></p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('103','7','','0','0','0','0','','','','<p>快来帮小青蛙填饱肚子吧!</p><p><strong>游戏玩法：</strong></p><p>1.点击鼠标即可跳跃</p><p>2.连续点击可连跳，最多4连跳</p><p><strong>游戏目标：</strong></p><p>在填饱肚子的同时，还要避免其他动物的伤害哦。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('104','7','','0','0','0','0','','','','<p>不要让可爱的兔子掉下去哦，兔子快跑吧。<br/>游戏玩法：<br/>遇到断木点击屏幕跳跃，躲过障碍。<br/>游戏目标：<br/>通关获得高分</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('105','7','','0','0','0','0','','','','<p>注意泡泡的弹射方向哦，快来消除所有泡泡吧!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕，点击播放键，选择关卡即可开始游戏。</p><p><strong>游戏目标：</strong></p><p>消除泡泡，获得更高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('106','7','','0','0','0','0','','','','<p>在爱情道路上，无论有多少困难，也绝不退缩!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕点击开始，即可开始游戏</p><p><strong>游戏玩法：</strong></p><p>1、跳过火圈获得分数;</p><p>2、点击左下按钮越过低处火圈;</p><p>3、点击右下按钮越过高处火圈</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('107','7','','0','0','0','0','','','','<p>这游戏太凶残，全世界只有3%的人可以玩到10000分!</p><p><strong>游戏玩法：</strong></p><p>将右侧提供的小六角组合放入大六角内，组成一行或多行，消除即可得分。</p><p><strong>游戏目标：</strong></p><p>直到放不下任何一块小六角组合，游戏失败，在游戏失败前尽可能获得高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('108','7','','0','0','0','0','','','','<p>全新的Q萌体验，快来消除糖果吧。</p><p><strong>如何开始：</strong></p><p>游戏运行完毕，点击播放键，选择关卡即可开始游戏</p><p><strong>游戏目标：</strong></p><p>消除糖果，获得高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('109','7','','0','0','0','0','','','','<p></p><p>40秒，你能洗多少个苹果呢?</p><p><strong>游戏玩法</strong>：</p><p>点击苹果上的污渍，清洗干净。</p><p><strong>游戏目标：</strong></p><p>在规定时间内清洗更多的苹果，获得高分。</p><p><strong><br/></strong><br/></p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('110','7','','0','0','0','0','','','','<p>快用最少的步骤来组合你的积木吧，记得三星通关哦!</p><p><strong>如何开始：</strong></p><p>游戏加载完毕点击播放键</p><p><strong>游戏玩法：</strong></p><p>鼠标拖动积木，将积木组合起来即可过关。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('111','7','','0','0','0','0','','','','<p>气球消除类游戏，如果可以，我可以消除整个页面!</p><p><strong>游戏玩法：</strong></p><p>滑动连接3个或更多相同颜色的气球，然后松开!</p><p><strong>游戏目标：</strong></p><p>规定时间内，消除气球获得更高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('112','7','','0','0','0','0','','','','<p>妖魔作祟，画个圈圈诅咒它，维护世界和平就交给你了!</p><p><strong>游戏玩法：</strong></p><p>根据妖魔头上的符号依次画出，消灭它们。</p><p><strong>游戏目标：</strong></p><p>尽可能消灭更多妖魔。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('113','7','','0','0','0','0','','','','<p>流畅的操作手感，让人体验到果冻的顺滑Q弹，找到同伴一起欢乐效果的感觉真棒!</p><p><strong>游戏玩法：</strong></p><p>1.5个糖果=重新填充</p><p>2.10个糖果=奖励炸弹</p><p>3.把饼干掉落在地上可以有高分奖励</p><p><strong>游戏目标：</strong></p><p>在规定步数内，达到消除数量，闯更多关!</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('114','7','','0','0','0','0','','','','<p>切水果游戏，水果盛宴你是否抵挡得住?</p><p><strong>游戏玩法：</strong></p><p>切水果得分，注意不要切到炸弹。</p><p><strong>游戏目标：</strong></p><p>切更多的水果来获得高分吧。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('115','7','','0','0','0','0','','','','<p>哥一定要挺住哦，18秒很简单的，是时候开始你的表演了。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕点击开始游戏</p><p><strong>游戏玩法：</strong></p><p>通过人像的移动躲避横行霸道的方块</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('116','7','','0','0','0','0','','','','<p>这是一款3D变形拼图游戏， 立体感十足， 更有挑战性! 想玩拼图，那必尝试下3D版拼图魔方游戏<br/></p><p><strong>如何开始：</strong></p><p>游戏加载完毕点击开始游戏，选择关卡即可开始游戏</p><p><strong>游戏目标：</strong></p><p>尽可能闯过更多关哦!</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('117','7','','0','0','0','0','','','','<p>能接多少杯，虐心又好玩，快来准备好你的水杯吧。</p><p><strong>如何开始：</strong></p><p>游戏加载完毕点击开始游戏，即可开始体验。</p><p><strong>游戏玩法：</strong></p><p>放水到红线的位置，或多或少都不可以，点击“开始游戏”就开始了，10秒的时间哦。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('118','7','','0','0','0','0','','','','<p>时间不等人，在规定时间内快速的计算36吧，考验你智商的时候到了。</p><p><strong>如何开始</strong>：</p><p>游戏加载完毕点击PLAY，即可开始游戏</p><p><strong>游戏目标：</strong></p><p>寻找和为36的两个方块来消除，在方块铺满前获更高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('119','7','','0','0','0','0','','','','<p>每个人心中都有一个英雄梦，面对敌人，勇敢的去进攻吧。</p><p><strong>游戏玩法：</strong></p><p>左右键负责攻击敌人，敌人触碰主角会掉血，血量为零则游戏结束。</p><p><strong>游戏目标：</strong></p><p>在60秒内消灭更多敌人，获得高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('120','7','','0','0','0','0','','','','<p>晨曦花园还是水上公园，地点任你挑选哦，快来体验花园中打高尔夫的舒适感吧！<strong><br/>游戏玩法</strong>：<br/></p><p>点击白球拉伸箭头，调整方向和力度释放白球，把球滚进洞里。</p><p><strong>游戏目标</strong>：</p><p>利用聪明才智，赢得最高分。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('121','7','','0','0','0','0','','','','<p>真正考验记忆力的游戏，60秒之内你能消除多少个图像呢，快来试试看吧。</p><p><strong>游戏玩法：</strong></p><p>进入游戏后，通过点击来找到相同的两张图像消除。</p><p><strong>游戏目标：</strong></p><p>规定时间内消除所有图像</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('122','7','','0','0','0','0','','','','<p><strong>游戏玩法</strong>：</p><p>鼠标点击控制换腿。</p><p><strong>游戏目标：</strong></p><p>争取走到最远。</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('123','7','','0','0','0','0','','','','<p><strong>如何开始</strong>：</p><p>点击游戏模式即可开始游戏。</p><p><strong>游戏玩法：</strong></p><p>大小跳跃躲避，坚持时间越长得分越高!</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('124','7','','0','0','0','0','','','','<p>不要被它朴实搞笑的画面所欺骗，因为这款游戏根本就不简单。<br/></p><p><strong>游戏玩法：</strong></p><p>点击鼠标控制拖鞋抽打神经猫，</p><p><strong>游戏目标：</strong></p><p>限时99秒内打出高分</p>');");
E_D("replace into `www_96kaifa_com_ecms_danji_data_1` values('125','7','','0','0','0','0','','','','<p>小章鱼们都喜欢快乐的拉拉手，一起手牵手谁都不想被单独留出来，小伙伴们快来帮帮八爪鱼们吧。游戏中关卡众多，赶紧来挑战吧!</p><p><strong>游戏目标</strong>：</p><p>合理移动八爪鱼、螃蟹，让它们手牵手即可过关。</p><p><strong>如何开始</strong>：</p><p>游戏加载完毕点击播放键，选择关卡即可开始游戏</p>');");

@include("../../inc/footer.php");
?>